# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/code/Nexys4DDR_Master.xdc

# IP: ip/dist_mem_gen_1/dist_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_1 || ORIG_REF_NAME==dist_mem_gen_1} -quiet] -quiet

# IP: ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet
